import {
  Project,
  Lead,
  Client,
  Quotation,
  Invoice,
  PaymentRecord,
  ProjectDocument,
  Milestone,
  ProjectMessage,
  Meeting,
  NotificationItem,
  AuditLog,
  TeamMember,
  AwardItem,
  TestimonialItem,
  ServiceItem,
  SiteStatistic,
  OfficeLocation,
} from '@/types';

// ==========================================
// 1. LIVRISE INFRASTRUCTURE OFFICES & CONTACT
// ==========================================
export const SEED_OFFICES: OfficeLocation[] = [
  {
    id: 'off-hq',
    title: 'LivRise Infrastructure',
    region: 'Engineering • Architecture • Infrastructure',
    address: '',
    city: '',
    state: '',
    pinCode: '',
    country: 'India',
    phone: '+91 6296603868',
    email: 'livriseinfrastructure@gmail.com',
    isHeadquarters: true,
  },
];

// ==========================================
// 2. POSITIONING TRUST STATEMENTS (NO FAKE NUMBERS)
// ==========================================
export const SEED_STATS: SiteStatistic[] = [
  {
    id: 'stat-eng',
    key: 'engineering_led',
    label: 'Core Discipline',
    valueDisplay: 'Engineering-Led',
    numericValue: 1,
    description: 'Structured engineering principles integrated across every project stage.',
    isVerified: true,
  },
  {
    id: 'stat-integrated',
    key: 'integrated_disciplines',
    label: 'Technical Scope',
    valueDisplay: 'Integrated Disciplines',
    numericValue: 1,
    description: 'Architecture, structural analysis, and infrastructure on a unified platform.',
    isVerified: true,
  },
  {
    id: 'stat-telemetry',
    key: 'digital_governance',
    label: 'Governance',
    valueDisplay: 'Digital Telemetry',
    numericValue: 1,
    description: 'Real-time project tracking, revision-controlled vault, and milestone transparency.',
    isVerified: true,
  },
  {
    id: 'stat-codal',
    key: 'quality_standards',
    label: 'Compliance',
    valueDisplay: 'Codal Compliance',
    numericValue: 1,
    description: 'Adherence to national building codes, structural safety, and engineering rigor.',
    isVerified: true,
  },
];

// ==========================================
// 3. LIVRISE INFRASTRUCTURE SERVICES (10 CORE SERVICES)
// ==========================================
export const SEED_SERVICES: ServiceItem[] = [
  {
    id: 'srv-arch',
    title: 'Architecture',
    slug: 'architecture',
    category: 'Architecture',
    summary: 'Contextual architectural planning, volumetric design, and spatial optimization.',
    headline: 'Functional Spaces Balanced with Architectural Precision and Natural Harmony',
    description: 'LivRise Infrastructure translates programmatic requirements into cohesive spatial forms. From master layout conceptualization to facade detailing, we balance aesthetic elegance with environmental responsiveness, daylight harvesting, and circulation efficiency.',
    capabilities: [
      'Concept Formulation & Massing Studies',
      'Comprehensive Master Layout Planning',
      'Residential, Commercial & Institutional Schemes',
      'Facade Engineering & Environmental Fenestration',
      'Statutory Municipal Compliance Drawings',
    ],
    processSteps: [
      { step: 1, title: 'Site Evaluation & Brief Analysis', desc: 'Analyzing site boundaries, sun angles, wind paths, and functional spatial allocations.' },
      { step: 2, title: 'Schematic Design & Iterations', desc: 'Developing zoning layouts, pedestrian flow charts, and functional floor plans.' },
      { step: 3, title: 'Design Development & Detailing', desc: 'Refining materiality, building elevations, cross-sections, and fenestrations.' },
      { step: 4, title: 'Statutory Documentation', desc: 'Compiling coordinated architectural drawings for municipal sanctions and site execution.' },
    ],
    deliverables: [
      'Architectural Layouts, Sections & Elevations',
      'Facade & Material Specifications',
      'Statutory Sanction Drawing Packages',
      'Door & Window Fenestration Schedules',
    ],
    targetIndustries: ['Residential Villas', 'Commercial Complexes', 'Educational Institutions', 'Hospitality & Resorts'],
    faqs: [
      { q: 'What is the architectural design process at LivRise Infrastructure?', a: 'We start with site analysis and spatial programming, progress to schematic layout options, refine 3D elevations and materials, and produce final sanction and execution drawings.' },
      { q: 'Do you integrate bioclimatic considerations?', a: 'Yes, our designs combine functional spatial ergonomics with scientific orientation, natural cross-ventilation, daylight optimization, and statutory compliance.' },
    ],
    icon: 'Compass',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
    isFeatured: true,
  },
  {
    id: 'srv-struct',
    title: 'Structural Engineering',
    slug: 'structural-engineering',
    category: 'Engineering',
    summary: 'Advanced structural modeling, load-bearing analysis, and resilient foundation systems.',
    headline: 'High-Integrity Structural Systems Engineered for Longevity and Safety',
    description: 'LivRise Infrastructure delivers comprehensive structural engineering consultancy spanning reinforced concrete frames, structural steel systems, foundation engineering, and seismic resilience. We leverage industry-standard computational finite-element tools to produce reliable, buildable, and code-compliant structural designs.',
    capabilities: [
      'Reinforced Concrete Frameworks & Shear Walls',
      'Structural Steel Truss & Portal Frame Design',
      'Geotechnical Foundation Analysis & Piling Schemes',
      'Seismic Resistance & Lateral Load Optimization',
      'Independent Structural Peer Review & Verification',
    ],
    processSteps: [
      { step: 1, title: 'Geotechnical & Loading Criteria', desc: 'Evaluating soil bearing capacity, environmental wind speed, and codal load combinations.' },
      { step: 2, title: 'Computational 3D Modeling', desc: 'Developing high-fidelity finite element models to simulate dynamic behavioral responses.' },
      { step: 3, title: 'Detailed Design & Stress Checks', desc: 'Optimizing member dimensions and reinforcement ratios for durability and economy.' },
      { step: 4, title: 'Good-for-Construction Detailing', desc: 'Issuing comprehensive construction drawings with clear bar bending and fabrication schedules.' },
    ],
    deliverables: [
      'Complete Structural Calculation Dossier',
      'Good-for-Construction (GFC) Drawing Sets',
      'Bar Bending & Structural Steel Schedules',
      'Foundation Layout & Column Axial Load Diagrams',
    ],
    targetIndustries: ['Commercial Real Estate', 'High-Rise Residential', 'Industrial Warehousing', 'Institutional Campuses'],
    faqs: [
      { q: 'What structural design codes do you follow?', a: 'We strictly adhere to IS 456 (Plain and Reinforced Concrete), IS 800 (General Construction in Steel), IS 1893 (Earthquake Resistant Design), and relevant international codes when required.' },
      { q: 'Do you provide Good-for-Construction (GFC) detailing?', a: 'Yes, complete GFC drawing packages along with structural calculation books, bar bending schedules, and foundation layouts are provided.' },
    ],
    icon: 'Layers',
    coverImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb186156f?q=80&w=1200&auto=format&fit=crop',
    isFeatured: true,
  },
  {
    id: 'srv-infra',
    title: 'Infrastructure',
    slug: 'infrastructure',
    category: 'Infrastructure',
    summary: 'Civil infrastructure planning, drainage networks, roads, and utilities engineering.',
    headline: 'Scalable Infrastructure Solutions for Sustainable Regional Growth',
    description: 'LivRise Infrastructure plans and engineers civil infrastructure that underpins modern communities. Our services encompass grading and earthwork optimization, stormwater management networks, arterial road geometry, and integrated utility distribution systems.',
    capabilities: [
      'Road Alignment & Pavement Design',
      'Stormwater Hydrology & Drainage Engineering',
      'Water Supply & Wastewater Network Planning',
      'Site Grading, Cut & Fill Optimization',
      'Utility Trenching & Infrastructure Corridors',
    ],
    processSteps: [
      { step: 1, title: 'Topographical & Hydrological Survey', desc: 'Mapping contour data, runoff patterns, and right-of-way boundaries.' },
      { step: 2, title: 'Network Hydraulic Modeling', desc: 'Simulating peak storm events and water demand flow networks.' },
      { step: 3, title: 'Pavement & Alignment Detailing', desc: 'Calculating structural pavement layers based on projected traffic volume.' },
      { step: 4, title: 'Integrated Services Coordination', desc: 'Producing unified composite utility layouts to prevent subsurface conflicts.' },
    ],
    deliverables: [
      'Road Cross-Sections & Longitudinal Profiles',
      'Stormwater Drainage Layouts & Invert Levels',
      'Water & Sewerage Reticulation Networks',
      'Composite Utility Corridor Plans',
    ],
    targetIndustries: ['Highway Authorities', 'Municipal Corporations', 'Industrial Corridors', 'Smart Cities'],
    faqs: [
      { q: 'What types of infrastructure projects do you undertake?', a: 'We specialize in bridge hydraulic and structural design, urban road networks, stormwater drainage networks, and water distribution infrastructure.' },
    ],
    icon: 'Building',
    coverImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200&auto=format&fit=crop',
    isFeatured: true,
  },
  {
    id: 'srv-masterplan',
    title: 'Master Planning',
    slug: 'master-planning',
    category: 'Architecture',
    summary: 'Large-scale land-use zoning, circulation frameworks, and township layout design.',
    headline: 'Strategic Land Planning for Forward-Thinking Developments',
    description: 'We craft comprehensive master plans that maximize land utility while safeguarding environmental assets. Our master planning framework establishes rational vehicular and pedestrian circulation networks, open-space green buffers, and phased development strategies.',
    capabilities: [
      'Comprehensive Land-Use Zoning',
      'Township & Mixed-Use Master Layouts',
      'Pedestrian & Vehicular Circulation Systems',
      'Open Space & Ecological Buffer Integration',
      'Phased Infrastructure Deployment Strategy',
    ],
    processSteps: [
      { step: 1, title: 'Land Asset & Boundary Assessment', desc: 'Analyzing physical site constraints, terrain contours, and statutory setbacks.' },
      { step: 2, title: 'Zoning & Density Distribution', desc: 'Allocating residential, commercial, and utility sectors for optimal synergy.' },
      { step: 3, title: 'Circulation & Open Space Networks', desc: 'Formulating primary, secondary, and tertiary mobility corridors.' },
      { step: 4, title: 'Master Plan Guidelines', desc: 'Establishing architectural and development design guidelines for phased execution.' },
    ],
    deliverables: [
      'Comprehensive Land-Use Master Plan',
      'Zoning & Density Allocation Matrix',
      'Circulation & Mobility Framework',
      'Phasing & Development Guidelines',
    ],
    targetIndustries: ['Township Developers', 'Government Planning Authorities', 'SEZs & Industrial Parks', 'Educational Campuses'],
    faqs: [
      { q: 'How do you handle statutory zoning compliance in master planning?', a: 'We incorporate regional town planning norms, FAR/FSI regulations, mandatory green buffers, and fire-tender access paths right from the conceptual stage.' },
    ],
    icon: 'Compass',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    isFeatured: false,
  },
  {
    id: 'srv-interior',
    title: 'Interior & Spatial Design',
    slug: 'interior-spatial-design',
    category: 'Architecture',
    summary: 'Ergonomic interior architecture, technical lighting, and acoustic planning.',
    headline: 'Thoughtfully Crafted Interiors Engineered for Living and Working',
    description: 'LivRise Infrastructure approaches interior spaces through an architectural lens, harmonizing ergonomics, materiality, acoustic performance, and energy-efficient lighting schemes. We produce comprehensive interior execution drawings that eliminate on-site ambiguity.',
    capabilities: [
      'Space Planning & Ergonomic Zoning',
      'Reflected Ceiling Plans (RCP) & Technical Lighting',
      'Bespoke Joinery & Millwork Detailing',
      'Acoustic Treatment & Thermal Comfort Planning',
      'Material Finishes & FF&E Specifications',
    ],
    processSteps: [
      { step: 1, title: 'Spatial Programming & Moodboards', desc: 'Establishing spatial hierarchy, daylight interaction, and material palettes.' },
      { step: 2, title: 'Detailed Plan Layouts', desc: 'Developing furniture layouts, circulation clearances, and partition schemes.' },
      { step: 3, title: 'Services Integration', desc: 'Coordinating HVAC diffusers, electrical conduits, and ceiling levels.' },
      { step: 4, title: 'Joinery Drawings & BOQ', desc: 'Publishing comprehensive millwork details and bill of quantities for procurement.' },
    ],
    deliverables: [
      'Furniture & Partition Layout Drawings',
      'Reflected Ceiling & Lighting Plans',
      'Detailed Joinery & Millwork Sheets',
      'Finishes & Hardware Schedule',
    ],
    targetIndustries: ['Corporate Headquarters', 'Luxury Residences', 'Retail Showrooms', 'Healthcare Facilities'],
    faqs: [
      { q: 'Do you handle technical MEP coordination for interiors?', a: 'Yes, our interior packages include reflected ceiling plans (RCP), lighting load calculations, HVAC diffuser placements, and acoustic treatments.' },
    ],
    icon: 'Building',
    coverImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1200&auto=format&fit=crop',
    isFeatured: false,
  },
  {
    id: 'srv-pm',
    title: 'Project Management',
    slug: 'project-management',
    category: 'Engineering',
    summary: 'End-to-end milestone management, contractor oversight, and site quality control.',
    headline: 'Rigorous Technical Governance from Inception to Project Handover',
    description: 'Our project management consultancy safeguards client capital and execution schedules. We implement structured milestone tracking, technical audit checkpoints, contractor coordination protocols, and quality assurance workflows across every project phase.',
    capabilities: [
      'Project Scheduling & Critical Path Method (CPM)',
      'Contractor Coordination & Technical Oversight',
      'Quality Assurance & Materials Verification',
      'Risk Identification & Schedule Mitigation',
      'Commissioning & Final Handover Governance',
    ],
    processSteps: [
      { step: 1, title: 'Baseline Schedule & Milestone Formulation', desc: 'Defining the critical path, deliverable timelines, and milestone checkpoints.' },
      { step: 2, title: 'Contractor Work Order Scoping', desc: 'Aligning technical specifications with tender schedules and deliverables.' },
      { step: 3, title: 'Site Inspection & Audit Verification', desc: 'Conducting periodic quality audits and concrete pour stage approvals.' },
      { step: 4, title: 'Closure & Handover Dossier', desc: 'Reviewing as-built drawings and certifying contractual milestones.' },
    ],
    deliverables: [
      'Master Project CPM Schedule',
      'Site Technical Inspection Audit Logs',
      'Milestone Progress Verification Certifications',
      'Final Project Commissioning Dossier',
    ],
    targetIndustries: ['Real Estate Developers', 'Public Sector Undertakings', 'Private Industrialists', 'Institutional Clients'],
    faqs: [
      { q: 'How do you monitor site execution and contractor accountability?', a: 'We deploy critical path method (CPM) scheduling, periodic milestone audits, material verification testing, and photographic log tracking through our digital platform.' },
    ],
    icon: 'Layers',
    coverImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1200&auto=format&fit=crop',
    isFeatured: false,
  },
  {
    id: 'srv-costing',
    title: 'Estimation & Cost Consultancy',
    slug: 'estimation-cost-consultancy',
    category: 'Engineering',
    summary: 'Detailed bill of quantities (BOQ), rate analysis, and material consumption modeling.',
    headline: 'Accurate Cost Engineering to Safeguard Project Viability',
    description: 'LivRise Infrastructure produces detailed quantity take-offs, itemized bills of quantities (BOQ), and market-tested rate analyses to ensure financial predictability. We prevent budget overruns through proactive value engineering and lifecycle cost calculations.',
    capabilities: [
      'Itemized Bill of Quantities (BOQ) Generation',
      'Rate Analysis & Material Market Benchmarking',
      'Preliminary Project Budget Feasibility Studies',
      'Contractor Tender Documentation & Bid Evaluation',
      'Monthly Valuation & Contractor RA Bill Certification',
    ],
    processSteps: [
      { step: 1, title: 'Drawing Quantity Take-Off', desc: 'Extracting precise material volumes from architectural and structural drawings.' },
      { step: 2, title: 'Rate Analysis Formulation', desc: 'Calculating labor, machinery, and material costs based on regional schedules.' },
      { step: 3, title: 'BOQ Assembly & Categorization', desc: 'Compiling structured trade-wise bills with technical item descriptions.' },
      { step: 4, title: 'Cost Optimization Review', desc: 'Identifying value engineering options to optimize capital expenditure.' },
    ],
    deliverables: [
      'Detailed Itemized Bill of Quantities (BOQ)',
      'Trade-Wise Cost Summary Statements',
      'Contractor Tender Price Estimates',
      'Material Consumption & Reconciliation Schedules',
    ],
    targetIndustries: ['Construction Contractors', 'Project Promoters', 'Banking Institutions', 'Asset Valuers'],
    faqs: [
      { q: 'What methodology is used for rate analysis?', a: 'We leverage regional schedules of rates calibrated against live local material and labor market indices to ensure realistic budget forecasts.' },
    ],
    icon: 'Layers',
    coverImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=1200&auto=format&fit=crop',
    isFeatured: false,
  },
  {
    id: 'srv-construction',
    title: 'Construction Consultancy',
    slug: 'construction-consultancy',
    category: 'Engineering',
    summary: 'On-site technical supervision, concrete mix vetting, and constructability audits.',
    headline: 'Bridging Design Engineering with On-Site Constructability',
    description: 'We provide specialized on-site technical advisory services to resolve site-level construction challenges. LivRise Infrastructure ensures that construction teams accurately interpret design intents, maintain required tolerances, and adhere to structural safety protocols.',
    capabilities: [
      'Constructability Audits & Clash Resolution',
      'Concrete Mix Design Vetting & Testing Protocol',
      'Temporary Works & Shuttering Scheme Evaluation',
      'Site Execution Guidance for Critical Framing',
      'Compliance Inspections for Structural Elements',
    ],
    processSteps: [
      { step: 1, title: 'Constructability Review', desc: 'Auditing design drawings against actual site conditions and access limitations.' },
      { step: 2, title: 'Pre-Pour Inspection', desc: 'Inspecting rebar placement, lap lengths, cover blocks, and formwork stability.' },
      { step: 3, title: 'Material Testing Oversight', desc: 'Verifying slump tests, cube compressive strengths, and mill test certificates.' },
      { step: 4, title: 'Site Technical Clarification', desc: 'Issuing technical field directives and non-conformance rectification plans.' },
    ],
    deliverables: [
      'Site Constructability Audit Reports',
      'Pre-Concreting Inspection Checklists',
      'Material Quality Verification Summaries',
      'Field Engineering Technical Directives',
    ],
    targetIndustries: ['General Contractors', 'Engineering Procurement Companies', 'Property Developers'],
    faqs: [
      { q: 'What is the role of constructability audits?', a: 'Constructability audits detect geometry clashes, rebar congestion, shuttering safety bottlenecks, and concrete placement challenges before mobilization.' },
    ],
    icon: 'Building',
    coverImage: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1200&auto=format&fit=crop',
    isFeatured: false,
  },
  {
    id: 'srv-analysis',
    title: 'Engineering Analysis',
    slug: 'engineering-analysis',
    category: 'Engineering',
    summary: 'Non-linear dynamic modeling, wind tunnel simulation coordination, and thermal analysis.',
    headline: 'High-Level Computational Analysis for Complex Engineering Challenges',
    description: 'For complex geometric structures and tall buildings, LivRise Infrastructure deploys specialized computational modeling. Our engineering analysis capabilities include non-linear dynamic response spectra, thermal gradient evaluation, and wind response correlation.',
    capabilities: [
      'Non-Linear Dynamic Response Spectrum Modeling',
      'High-Rise Wind Response & Vortex Shedding Analysis',
      'Thermal Gradient & Heat Transfer Calculations',
      'Foundation-Soil Dynamic Interaction Modeling',
      'Structural Vibration & Modal Analysis',
    ],
    processSteps: [
      { step: 1, title: 'Physics-Based Problem Definition', desc: 'Defining boundary conditions, loading envelopes, and material non-linearities.' },
      { step: 2, title: 'Finite Element Discretization', desc: 'Constructing refined mesh models with appropriate element formulations.' },
      { step: 3, title: 'Solver Execution & Convergence Checks', desc: 'Running dynamic iterations and validating modal participation factors.' },
      { step: 4, title: 'Engineering Synthesis & Report', desc: 'Extracting critical drift indices, base shears, and behavioral conclusions.' },
    ],
    deliverables: [
      'Detailed Finite Element Analysis Report',
      'Modal Acceleration & Displacement Charts',
      'Thermal Stress & Deflection Contour Diagrams',
      'Executive Engineering Recommendations',
    ],
    targetIndustries: ['Specialized Infrastructure', 'High-Rise Developers', 'Heavy Industrial Plants'],
    faqs: [
      { q: 'When is non-linear dynamic analysis necessary?', a: 'Non-linear dynamic and push-over analyses are required for irregular high-rise structures, structures in higher seismic zones, and facilities with high post-earthquake operational importance.' },
    ],
    icon: 'Layers',
    coverImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?q=80&w=1200&auto=format&fit=crop',
    isFeatured: false,
  },
  {
    id: 'srv-retro',
    title: 'Retrofitting & Rehabilitation',
    slug: 'retrofitting-rehabilitation',
    category: 'Specialized & R&D',
    summary: 'Structural health audits, column jacketing, carbon fiber wrapping, and building life extension.',
    headline: 'Extending the Structural Life and Resilience of Existing Assets',
    description: 'We assess aged or distressed structures and engineer specialized remedial interventions. Our retrofitting solutions encompass reinforced concrete jacketing, fiber-reinforced polymer (FRP) wrapping, micro-concreting, and foundation underpinning to restore load capacity and meet modern seismic codes.',
    capabilities: [
      'Non-Destructive Testing (NDT) Interpretation',
      'RC Column & Beam Jacketing Design',
      'Carbon Fiber Reinforced Polymer (CFRP) Strengthening',
      'Foundation Underpinning & Settlement Mitigation',
      'Structural Life Assessment & Monitoring',
    ],
    processSteps: [
      { step: 1, title: 'Condition Survey & NDT Mapping', desc: 'Conducting rebound hammer, ultrasonic pulse velocity, and core sampling checks.' },
      { step: 2, title: 'Residual Strength Assessment', desc: 'Simulating remaining capacity and identifying deficient structural members.' },
      { step: 3, title: 'Retrofit Scheme Engineering', desc: 'Designing jacketing details or CFRP composites with appropriate development lengths.' },
      { step: 4, title: 'Execution Methodology & QA', desc: 'Formulating step-by-step surface preparation, bonding, and curing protocols.' },
    ],
    deliverables: [
      'Structural Health & Integrity Assessment Report',
      'Detailed Retrofitting & Jacketing Drawing Sets',
      'CFRP / Steel Composite Strengthening Specs',
      'Quality Verification & Proof-Testing Protocols',
    ],
    targetIndustries: ['Heritage Structures', 'Industrial Plants', 'Commercial Assets', 'Distressed Residential'],
    faqs: [
      { q: 'Can a severely distressed building be safely retrofitted?', a: 'Yes. With modern carbon fiber composite wrapping, steel bracing, and micro-concrete column jacketing, deficient or distressed members can be restored to full structural compliance.' },
    ],
    icon: 'Layers',
    coverImage: 'https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?q=80&w=1200&auto=format&fit=crop',
    isFeatured: true,
  },
];

// ==========================================
// 4. CLEAN CMS COLLECTIONS (EMPTY BY DEFAULT)
// ==========================================
// Projects are currently being curated
export const SEED_PROJECTS: Project[] = [];

// Verified Leadership
export const SEED_TEAM: TeamMember[] = [
  {
    id: 'team-iman-khanra',
    name: 'Iman Khanra',
    position: 'Founder & Principal Director',
    department: 'Executive Leadership',
    photoUrl: '/images/iman-khanra.jpg',
    biography: 'Iman Khanra leads LivRise Infrastructure with a solid foundation in civil engineering and infrastructure delivery. Holding a Diploma in Civil Engineering from Contai Polytechnic and a Bachelor of Technology (B.Tech) in Civil Engineering from Techno India University, he oversees structural design vetting, engineering analysis, and modern project execution across LivRise engagements.',
    education: 'B.Tech in Civil Engineering (Techno India University) • Diploma in Civil Engineering (Contai Polytechnic)',
    experienceYears: 'Professional',
    expertise: [
      'Civil Engineering',
      'Structural Analysis',
      'Infrastructure Planning',
      'Construction Management',
      'Design Compliance',
    ],
    socialLinks: {
      email: 'livriseinfrastructure@gmail.com',
    },
  },
];

// Clean awards starting empty - no fake claims
export const SEED_AWARDS: AwardItem[] = [];

// Clean testimonials starting empty - no fake claims
export const SEED_TESTIMONIALS: TestimonialItem[] = [];

// ==========================================
// 5. GENERIC DEMO WORKFLOW DATA (FOR DEMO/TESTING)
// ==========================================
export const SEED_CLIENTS: Client[] = [
  {
    id: 'cl-demo-01',
    clientCode: 'LIV-CL-2026-0001',
    profileId: 'usr-client-demo',
    fullName: 'Enterprise Client Representative',
    companyName: 'Apex Development Group',
    email: 'client@livriseinfrastructure.com',
    phone: '+91 98000 00000',
    billingAddress: 'Corporate Tower, Commercial District',
    city: 'Kolkata',
    state: 'West Bengal',
    country: 'India',
    pinCode: '700001',
    activeProjectsCount: 1,
    totalSpent: 450000,
    createdAt: '2026-01-15',
    primaryContact: {
      name: 'Client Operations Director',
      email: 'client@livriseinfrastructure.com',
      phone: '+91 98000 00000',
      designation: 'Director of Projects',
      city: 'Kolkata',
      state: 'West Bengal',
    },
  },
];

export const SEED_LEADS: Lead[] = [
  {
    id: 'lead-demo-01',
    enquiryNumber: 'LIV-2026-00001',
    fullName: 'Prospective Client',
    name: 'Prospective Client',
    email: 'lead@livriseinfrastructure.com',
    phone: '+91 98000 00000',
    preferredContactMethod: 'email',
    serviceRequired: 'Structural Engineering',
    servicesRequested: ['Structural Engineering', 'Architecture'],
    projectType: 'Commercial',
    country: 'India',
    state: 'West Bengal',
    city: 'Kolkata',
    pinCode: '700001',
    plotArea: '15,000 Sq.Ft.',
    builtUpArea: '60,000 Sq.Ft.',
    numberOfFloors: 'G+12 Storeys',
    currentStage: 'Concept / Planning Stage',
    estimatedBudget: '₹2 Crores - ₹10 Crores',
    expectedStartDate: 'Q1 2027',
    requirements: 'Comprehensive structural analysis and architectural coordination for commercial hub.',
    status: 'New Leads',
    source: 'LivRise Smart Project Enquiry',
    createdAt: '2026-09-28',
    updatedAt: '2026-09-28',
    location: {
      country: 'India',
      state: 'West Bengal',
      city: 'Kolkata',
      pinCode: '700001',
    },
    details: {
      plotArea: '15,000 Sq.Ft.',
      builtUpArea: '60,000 Sq.Ft.',
      floors: 'G+12 Storeys',
      currentStage: 'Concept / Planning Stage',
      estimatedBudget: '₹2 Crores - ₹10 Crores',
      expectedStartDate: 'Q1 2027',
    },
  },
];

export const SEED_QUOTATIONS: Quotation[] = [
  {
    id: 'qt-demo-01',
    quotationNumber: 'LIV-QT-2026-0001',
    clientId: 'cl-demo-01',
    clientName: 'Apex Development Group',
    clientEmail: 'client@livriseinfrastructure.com',
    serviceTitle: 'Structural Design & Architectural Vetting',
    items: [
      {
        id: 'itm-01',
        itemDescription: 'Three-Dimensional Structural Finite Element Analysis & Foundation Detailing',
        description: 'Three-Dimensional Structural Finite Element Analysis & Foundation Detailing',
        quantity: 1,
        unit: 'Lump Sum',
        unitPrice: 280000,
        totalPrice: 280000,
        total: 280000,
      },
      {
        id: 'itm-02',
        itemDescription: 'Architectural Peer Review & Municipal Compliance Certification',
        description: 'Architectural Peer Review & Municipal Compliance Certification',
        quantity: 1,
        unit: 'Certification',
        unitPrice: 70000,
        totalPrice: 70000,
        total: 70000,
      },
    ],
    subtotal: 350000,
    discountAmount: 0,
    taxRatePercent: 18,
    taxAmount: 63000,
    tax: 63000,
    grandTotal: 413000,
    currency: 'INR',
    validUntil: '2026-12-31',
    termsAndConditions: 'Standard LivRise Infrastructure engineering consultancy terms. 40% advance upon project initiation, 40% upon preliminary structural submission, 20% upon final municipal sanction approvals.',
    terms: [
      '40% advance upon project initiation and work order execution.',
      '40% upon submission of preliminary structural drawings and calculations.',
      '20% upon final municipal sanction approvals.',
    ],
    notes: 'Generated via LivRise Infrastructure Digital Operations Console.',
    status: 'Sent',
    createdAt: '2026-09-25',
  },
];

export const SEED_INVOICES: Invoice[] = [
  {
    id: 'inv-demo-01',
    invoiceNumber: 'LIV-INV-2026-0001',
    clientId: 'cl-demo-01',
    clientName: 'Apex Development Group',
    clientEmail: 'client@livriseinfrastructure.com',
    quotationNumber: 'LIV-QT-2026-0001',
    items: [
      {
        id: 'inv-item-01',
        description: 'Milestone 1 Completion: Geotechnical Evaluation & Substructure Design Layouts',
        quantity: 1,
        unit: 'Lot',
        unitPrice: 150000,
        totalPrice: 150000,
        total: 150000,
      },
    ],
    subtotal: 150000,
    taxAmount: 27000,
    tax: 27000,
    discountAmount: 0,
    totalAmount: 177000,
    total: 177000,
    amountPaid: 177000,
    balanceDue: 0,
    currency: 'INR',
    issueDate: '2026-09-10',
    dueDate: '2026-09-25',
    status: 'Paid',
    paymentTerms: 'Settled in full via Corporate NEFT bank wire.',
    notes: 'Official Milestone Tax Invoice issued by LivRise Infrastructure.',
    createdAt: '2026-09-10',
  },
];

export const SEED_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-demo-01',
    paymentReference: 'PAY-2026-00001',
    invoiceId: 'inv-demo-01',
    invoiceNumber: 'LIV-INV-2026-0001',
    clientId: 'cl-demo-01',
    clientName: 'Apex Development Group',
    amount: 177000,
    currency: 'INR',
    paymentMethod: 'NEFT / Direct Bank Wire',
    gateway: 'Corporate Treasury Settlement',
    transactionId: 'UTR-LIVRISE-20260912-9988',
    status: 'Successful',
    paymentDate: '2026-09-12',
    paidAt: '2026-09-12',
    notes: 'Verified and reconciled by LivRise Infrastructure Treasury Desk.',
  },
];

export const SEED_DOCUMENTS: ProjectDocument[] = [
  {
    id: 'doc-demo-01',
    projectId: 'demo-prj-01',
    projectName: 'Demo Engineering Project',
    folder: 'Structural',
    category: 'Structural',
    name: 'Foundation & Framing Calculation Dossier',
    title: 'Foundation & Framing Calculation Dossier',
    fileName: 'LIVRISE_Structural_Model_REV01.pdf',
    currentVersion: 'REV01',
    version: 'REV01',
    storagePath: '/vault/LIVRISE_Structural_Model_REV01.pdf',
    fileSizeBytes: 4200000,
    fileSize: '4.2 MB',
    fileType: 'application/pdf',
    fileExtension: 'pdf',
    status: 'Approved',
    uploadedBy: 'LivRise Engineering Desk',
    uploadedAt: '2026-09-20',
    isClientAccessible: true,
    isClientVisible: true,
  },
];

export const SEED_MILESTONES: Milestone[] = [
  {
    id: 'ms-demo-01',
    projectId: 'demo-prj-01',
    name: 'Concept & Geotechnical Feasibility',
    description: 'Evaluation of site parameters, soil bearing capacity, and preliminary structural zoning.',
    status: 'Completed',
    ownerName: 'LivRise Lead Consultant',
    owner: 'LivRise Lead Consultant',
    startDate: '2026-08-01',
    dueDate: '2026-08-20',
    progressPercentage: 100,
    progress: 100,
    displayOrder: 1,
  },
  {
    id: 'ms-demo-02',
    projectId: 'demo-prj-01',
    name: 'Three-Dimensional Structural Modeling',
    description: 'Dynamic response spectra, frame modeling, and member stress checks.',
    status: 'In Progress',
    ownerName: 'LivRise Lead Consultant',
    owner: 'LivRise Lead Consultant',
    startDate: '2026-08-21',
    dueDate: '2026-10-15',
    progressPercentage: 65,
    progress: 65,
    displayOrder: 2,
  },
];

export const SEED_MESSAGES: ProjectMessage[] = [
  {
    id: 'msg-demo-01',
    projectId: 'demo-prj-01',
    senderId: 'usr-client-demo',
    senderName: 'Client Representative',
    senderRole: 'client',
    messageText: 'Hello LivRise engineering team, we have reviewed the preliminary foundation layout. Can we coordinate a virtual review on the column grid spacing?',
    isRead: true,
    createdAt: '2026-09-26 10:30 AM',
  },
  {
    id: 'msg-demo-02',
    projectId: 'demo-prj-01',
    senderId: 'usr-admin-livrise',
    senderName: 'LivRise Engineering Lead',
    senderRole: 'admin',
    messageText: 'Certainly. Our structural engineering desk has scheduled the coordination review. The revised grid calculations have been uploaded to your document vault for review.',
    isRead: true,
    createdAt: '2026-09-26 11:15 AM',
  },
];

export const SEED_MEETINGS: Meeting[] = [
  {
    id: 'mtg-demo-01',
    title: 'Structural Grid & Foundation Review',
    projectId: 'demo-prj-01',
    projectName: 'Demo Engineering Project',
    clientId: 'cl-demo-01',
    clientName: 'Apex Development Group',
    organizerName: 'LivRise Engineering Lead',
    meetingDate: '2026-10-05',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    meetingType: 'Virtual (Google Meet / Zoom)',
    meetingUrl: 'https://meet.google.com/livrise-review',
    agenda: 'Technical review of column axial loads, shear wall placements, and municipal sanction requirements.',
    status: 'Scheduled',
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-demo-01',
    recipientRole: 'admin',
    title: 'New Project Enquiry Received',
    message: 'Enquiry LIV-2026-00001 submitted for Commercial Structural Engineering.',
    linkUrl: '/admin/leads',
    type: 'enquiry',
    isRead: false,
    createdAt: '2026-09-28',
  },
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-demo-01',
    actorName: 'System Administrator',
    actorEmail: 'admin@livriseinfrastructure.com',
    action: 'system.initialization',
    entity: 'system',
    entityId: 'SYS-INIT-2026',
    metadata: { platform: 'LivRise Infrastructure Platform', status: 'Ready' },
    ipAddress: '127.0.0.1',
    timestamp: '2026-09-30T10:00:00.000Z',
  },
];
